@api = http://localhost:8000/api
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYW9sby5zYWxhemFyQGV4YW1wbGUuY29tIiwidXNlcl9pZCI6MSwicm9sZV9pZCI6MSwiZXhwIjoxNzczMjgyNDExfQ.BrfSB97obS_4o4l5UfKCaNvxcrEeE4fMLS1aTaga7PY
### Permissions Endpoints ###
GET {{api}}/permissions
Authorization: Bearer {{user_token}}

###
GET {{api}}/permissions?skip=0&limit=8
Authorization: Bearer {{user_token}}
###
GET {{api}}/permissions?skip=8&limit=8
Authorization: Bearer {{user_token}}

###
POST {{api}}/permissions
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "name": "write:events",
  "description": "Permission to write event information"
}

###
GET {{api}}/permissions/admin/permissions
Authorization: Bearer {{user_token}}

###
### Assign permission to role
POST {{api}}/permissions/roles/assign?permission_name=write:events&role_name=musician
Authorization: Bearer {{user_token}}

###
### Remove permission from role
POST {{api}}/permissions/roles/remove?permission_name=write:user_roles&role_name=admin
Authorization: Bearer {{user_token}}

###
### Get permissions for a specific role
GET {{api}}/permissions/admin/permissions
Authorization: Bearer {{user_token}}

###
### Get roles that have a specific permission
GET {{api}}/permissions/role/write:user_roles/roles
Authorization: Bearer {{user_token}}

###

PATCH {{api}}/permissions/1
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "description": "Updated description for the permission"
}

###

DELETE {{api}}/permissions/read:user_roles
Authorization : Bearer {{user_token}}

###



### Get all user roles
GET {{api}}/user-roles/
Authorization: Bearer {{user_token}}
###

### Get a specific user role
GET {{api}}/user-roles/admin

###

### Create a new user role
POST {{api}}/user-roles/
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "name": "admin",
  "description": "Administrator role"
}

###

### Update an existing user role (PATCH)
PATCH {{api}}/user-roles/1
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "name": "admin",
  "description": "Administrator role updated"
}

###

### Replace an existing user role (PUT)
PUT {{api}}/user-roles/
Content-Type: application/json

{
  "id": 2,
  "name": "superadmin",
  "description": "Super administrator role"
}

###
### Delete a user role
DELETE {{api}}/user-roles/musician
Authorization: Bearer {{user_token}}

###
### USERS ENDPOINTS ###
### Get all users (requires authentication)
GET {{api}}/users/
Authorization: Bearer {{user_token}}

### Post a new user
POST {{api}}/users/
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "name": "juan",
  "lastname": "perez",
  "second_lastname": "villarroel",
  "email": "juan.perez@example.com",
  "password": "perez",
  "role_id": 1
}

### Get a specific user
GET {{api}}/users/paolo.salazar@example.com
Authorization: Bearer {{user_token}}

### Get a specific user by Id
GET {{api}}/users/1
Authorization: Bearer {{user_token}}

### Update an existing user (PATCH)
PATCH {{api}}/users/
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "name": "Janet",
  "lastname": "Smith",
  "second_lastname": "Johnson",
  "email": "jane.smith@example.com",
  "role_id": 3
}

###

### Update user password (PATCH)
PATCH {{api}}/users/jane.smith@example.com/password
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "current_password": "newsecurepassword456",
  "new_password": "newsecurepassword123"
}

###
### AUTHENTICATION ENDPOINTS ###
### Initialize token variable

### Login user
POST {{api}}/users/login
Content-Type: application/json

{
  "email": "paolo.salazar@example.com",
  "password": "salazar"
}

### Get Current User Info
GET {{api}}/users/me
Authorization: Bearer {{user_token}}