@api = http://localhost:8000/api
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYW9sby5zYWxhemFyQGV4YW1wbGUuY29tIiwidXNlcl9pZCI6MSwicm9sZV9pZCI6MSwiZXhwIjoxNzcyMTkxNzc3fQ.HC-m7MtDh3K6D7E1Y2b-0XXR6IE6DDOGrB-mVY9r3M4
### Permissions Endpoints ###
GET {{api}}/permissions
Authorization: Bearer {{user_token}}

###
POST {{api}}/permissions
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "name": "read:events",
  "description": "Permission to read event information"
}

###
GET {{api}}/permissions/admin/permissions
Authorization: Bearer {{user_token}}

###
### Assign permission to role
POST {{api}}/permissions/roles/assign?permission_name=read:events&role_name=admin
Authorization: Bearer {{user_token}}

###
### Remove permission from role
POST {{api}}/permissions/roles/remove?permission_name=write:user_roles&role_name=admin
Authorization: Bearer {{user_token}}

###
### Get permissions for a specific role
GET {{api}}/permissions/admin/permissions
Authorization: Bearer {{user_token}}

###
### Get roles that have a specific permission
GET {{api}}/permissions/role/write:user_roles/roles
Authorization: Bearer {{user_token}}

###



### Get all user roles
GET {{api}}/user-roles/
Authorization: Bearer {{user_token}}
###

### Get a specific user role
GET {{api}}/user-roles/admin

###

### Create a new user role
POST {{api}}/user-roles/
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "name": "editor",
  "description": "Content editor role"
}

###

### Update an existing user role (PATCH)
PATCH {{api}}/user-roles/
Content-Type: application/json

{
  "name": "moderator",
  "description": "Content moderator role changed"
}

###

### Replace an existing user role (PUT)
PUT {{api}}/user-roles/
Content-Type: application/json

{
  "id": 2,
  "name": "superadmin",
  "description": "Super administrator role"
}

###
### Delete a user role
DELETE {{api}}/user-roles/superadmin

###
### USERS ENDPOINTS ###
### Get all users (requires authentication)
GET {{api}}/users/
Authorization: Bearer {{user_token}}

### Post a new user
POST {{api}}/users/
Content-Type: application/json

{
  "name": "paolo",
  "lastname": "salazar",
  "second_lastname": "villarroel",
  "email": "paolo.salazar@example.com",
  "password": "salazar",
  "role_id": 1
}

### Get a specific user
GET {{api}}/users/paolo.salazar@example.com
Authorization: Bearer {{user_token}}

### Update an existing user (PATCH)
PATCH {{api}}/users/
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "name": "Janet",
  "lastname": "Smith",
  "second_lastname": "Johnson",
  "email": "jane.smith@example.com",
  "role_id": 3
}

###

### Update user password (PATCH)
PATCH {{api}}/users/jane.smith@example.com/password
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
  "current_password": "newsecurepassword456",
  "new_password": "newsecurepassword123"
}

###
### AUTHENTICATION ENDPOINTS ###
### Initialize token variable

### Login user
POST {{api}}/users/login
Content-Type: application/json

{
  "email": "paolo.salazar@example.com",
  "password": "salazar"
}

### Get Current User Info
GET {{api}}/users/me
Authorization: Bearer {{user_token}}