"""create musician_availability table

Revision ID: 3b488a755f4d
Revises: 36dfd2d656e5
Create Date: 2026-04-09 04:50:26.743258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b488a755f4d'
down_revision: Union[str, None] = '36dfd2d656e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musician_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('musician_id', sa.Integer(), nullable=False),
    sa.Column('unavailable_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('unavailable_date >= CURRENT_DATE', name='check_unavailable_date_future'),
    sa.ForeignKeyConstraint(['musician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musician_availability')
    # ### end Alembic commands ###
