"""Sync database with models

Revision ID: 5e1045d595ae
Revises: add_phone_number_to_users
Create Date: 2026-03-20 17:41:29.995376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e1045d595ae'
down_revision: Union[str, None] = 'add_phone_number_to_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop user_details table and index if they exist (using raw SQL for safety)
    # This is needed because user_details was removed from models but migration may run on fresh DB
    op.execute("""
        DROP INDEX IF EXISTS ix_user_details_id;
        DROP TABLE IF EXISTS user_details;
    """)
    op.add_column('events', sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('is_all_day', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('events', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'])
    op.drop_column('events', 'time')
    op.drop_column('events', 'reference_phone')
    op.drop_column('events', 'date')
    op.drop_column('events', 'created_by')
    op.drop_constraint('role_permissions_permission_id_fkey', 'role_permissions', type_='foreignkey')
    op.drop_constraint('role_permissions_role_id_fkey', 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'user_roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key('role_permissions_role_id_fkey', 'role_permissions', 'user_roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('role_permissions_permission_id_fkey', 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='RESTRICT')
    op.add_column('events', sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('reference_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'user_id')
    op.drop_column('events', 'is_all_day')
    op.drop_column('events', 'end_datetime')
    op.drop_column('events', 'start_datetime')
    op.create_table('user_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('detail_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('detail_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_details_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_details_pkey'),
    sa.UniqueConstraint('user_id', 'detail_type', name='uq_user_detail_type', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_user_details_id', 'user_details', ['id'], unique=False)
    # ### end Alembic commands ###
