"""UPDATE MusicianEventPayment table

Revision ID: db95bce4c6a5
Revises: 76129873702f
Create Date: 2026-04-14 07:15:46.341146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db95bce4c6a5'
down_revision: Union[str, None] = '76129873702f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
